---
- name: Configure MOTD on router
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: cisco

  tasks:
    - name: Set MOTD banner
      ios_banner:
        banner: motd
        text: "Authorized users only! Managed by 66070138"
